#!/usr/bin/env python3
"""
postmortem_generator.py
Generates structured blameless postmortem documents from incident data.
Tracks follow-up actions and converts recurring incidents into
permanent automated fixes.
Built from real postmortem practice at Southwest Airlines.

Usage:
    python postmortem_generator.py --incident INC-1234 --title "Payment API Outage"
    python postmortem_generator.py --list
"""

import argparse
import json
import logging
from datetime import datetime
from pathlib import Path

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

POSTMORTEM_TEMPLATE = """
# Postmortem — {title}

**Incident ID:**     {incident_id}
**Date:**           {date}
**Severity:**       {severity}
**Duration:**       {duration_minutes} minutes
**Status:**         {status}

---

## Summary

{summary}

---

## Timeline

| Time | Event |
|------|-------|
{timeline}

---

## Root Cause

{root_cause}

---

## Impact

- **Services affected:** {services_affected}
- **Users impacted:** {users_impacted}
- **Revenue impact:** {revenue_impact}
- **SLO impact:** Error budget consumed: {error_budget_consumed}%

---

## What Went Well

{went_well}

---

## What Went Wrong

{went_wrong}

---

## Action Items

| Action | Owner | Due Date | Status |
|--------|-------|----------|--------|
{action_items}

---

## Lessons Learned

{lessons_learned}

---

## Detection

- **Time to detect (MTTD):** {mttd_minutes} minutes
- **Time to resolve (MTTR):** {mttr_minutes} minutes
- **Detected by:** {detected_by}

---

*This postmortem is blameless. The goal is systematic improvement, not blame.*
*Generated by postmortem-automation toolkit*
"""


class PostmortemGenerator:
    def __init__(self, output_dir: str = "postmortems"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def generate(self, incident_data: dict) -> str:
        incident_id  = incident_data.get("incident_id", "INC-UNKNOWN")
        title        = incident_data.get("title", "Untitled Incident")
        date         = incident_data.get("date", datetime.utcnow().strftime("%Y-%m-%d"))
        severity     = incident_data.get("severity", "P2")
        duration     = incident_data.get("duration_minutes", 0)
        status       = incident_data.get("status", "Resolved")
        summary      = incident_data.get("summary", "TBD")
        root_cause   = incident_data.get("root_cause", "TBD")
        went_well    = incident_data.get("went_well", "TBD")
        went_wrong   = incident_data.get("went_wrong", "TBD")
        lessons      = incident_data.get("lessons_learned", "TBD")
        mttd         = incident_data.get("mttd_minutes", 0)
        mttr         = incident_data.get("mttr_minutes", 0)
        detected_by  = incident_data.get("detected_by", "PagerDuty alert")
        services     = incident_data.get("services_affected", "TBD")
        users        = incident_data.get("users_impacted", "TBD")
        revenue      = incident_data.get("revenue_impact", "TBD")
        error_budget = incident_data.get("error_budget_consumed", 0)

        # Format timeline
        timeline_rows = "\n".join([
            f"| {t.get('time', '')} | {t.get('event', '')} |"
            for t in incident_data.get("timeline", [])
        ]) or "| TBD | TBD |"

        # Format action items
        action_rows = "\n".join([
            f"| {a.get('action', '')} | {a.get('owner', '')} | {a.get('due_date', '')} | {a.get('status', 'Open')} |"
            for a in incident_data.get("action_items", [])
        ]) or "| TBD | TBD | TBD | Open |"

        content = POSTMORTEM_TEMPLATE.format(
            title=title,
            incident_id=incident_id,
            date=date,
            severity=severity,
            duration_minutes=duration,
            status=status,
            summary=summary,
            timeline=timeline_rows,
            root_cause=root_cause,
            services_affected=services,
            users_impacted=users,
            revenue_impact=revenue,
            error_budget_consumed=error_budget,
            went_well=went_well,
            went_wrong=went_wrong,
            action_items=action_rows,
            lessons_learned=lessons,
            mttd_minutes=mttd,
            mttr_minutes=mttr,
            detected_by=detected_by,
        )

        filename = f"{incident_id}-{title.lower().replace(' ', '-')}.md"
        output_path = self.output_dir / filename

        with open(output_path, "w") as f:
            f.write(content)

        logger.info(f"Postmortem generated: {output_path}")
        return str(output_path)

    def list_postmortems(self) -> None:
        files = list(self.output_dir.glob("*.md"))
        if not files:
            print("No postmortems found")
            return
        print(f"\nPostmortems ({len(files)} total):")
        for f in sorted(files):
            print(f"  - {f.name}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate blameless postmortem documents")
    parser.add_argument("--incident", help="Incident ID e.g. INC-1234")
    parser.add_argument("--title", help="Incident title")
    parser.add_argument("--severity", default="P2", choices=["P1", "P2", "P3"])
    parser.add_argument("--duration", type=int, default=60, help="Duration in minutes")
    parser.add_argument("--list", action="store_true", help="List all postmortems")
    parser.add_argument("--output-dir", default="postmortems")
    return parser.parse_args()


def main():
    args = parse_args()
    generator = PostmortemGenerator(output_dir=args.output_dir)

    if args.list:
        generator.list_postmortems()
        return

    if not args.incident or not args.title:
        print("Provide --incident and --title")
        print("Example: python postmortem_generator.py --incident INC-1234 --title 'API Outage'")
        return

    incident_data = {
        "incident_id": args.incident,
        "title": args.title,
        "severity": args.severity,
        "duration_minutes": args.duration,
        "date": datetime.utcnow().strftime("%Y-%m-%d"),
        "status": "Resolved",
        "timeline": [
            {"time": "00:00", "event": "Alert triggered in PagerDuty"},
            {"time": "00:05", "event": "On-call engineer acknowledged"},
            {"time": "00:15", "event": "Root cause identified"},
            {"time": "00:45", "event": "Fix deployed"},
            {"time": "01:00", "event": "Service fully recovered"},
        ],
        "action_items": [
            {"action": "Add alerting for early detection", "owner": "SRE Team", "due_date": "2026-06-01", "status": "Open"},
            {"action": "Update runbook with fix steps", "owner": "On-call Engineer", "due_date": "2026-05-15", "status": "Open"},
            {"action": "Automate remediation script", "owner": "SRE Team", "due_date": "2026-06-15", "status": "Open"},
        ],
    }

    output_path = generator.generate(incident_data)
    print(f"\nPostmortem created: {output_path}")


if __name__ == "__main__":
    main()
